"use client";

import { useState } from "react";
import DashboardLayout from "@/components/dashboard-layout";
import { Calendar, CheckCircle2, Circle, AlertCircle, Sparkles, Loader2 } from "lucide-react";
import { useQuery, useAction } from "convex/react";
import { api } from "../../../../convex/_generated/api";
import { useUser } from "@clerk/nextjs";

const StandupCard = ({ author, yesterday, today, blockers, date }: any) => (
  <div className="p-6 rounded-2xl border bg-card/50 hover:border-primary/30 transition-all group">
    <div className="flex items-center gap-3 mb-6">
      <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold">
        {author[0]}
      </div>
      <div>
        <h3 className="font-bold">{author}</h3>
        <p className="text-xs text-muted-foreground">Generated by AI on {date}</p>
      </div>
    </div>

    <div className="space-y-6">
      <div>
        <h4 className="text-xs font-bold text-muted-foreground uppercase mb-3 flex items-center gap-2">
          <CheckCircle2 size={14} className="text-green-500" />
          Yesterday
        </h4>
        <ul className="text-sm space-y-2 text-foreground/80">
          {yesterday.map((item: string, i: number) => (
            <li key={i} className="flex gap-2">
              <span className="text-primary">•</span> {item}
            </li>
          ))}
        </ul>
      </div>

      <div>
        <h4 className="text-xs font-bold text-muted-foreground uppercase mb-3 flex items-center gap-2">
          <Circle size={14} className="text-primary" />
          Today
        </h4>
        <ul className="text-sm space-y-2 text-foreground/80">
          {today.map((item: string, i: number) => (
            <li key={i} className="flex gap-2">
              <span className="text-primary">•</span> {item}
            </li>
          ))}
        </ul>
      </div>

      {blockers && blockers.length > 0 && (
        <div className="p-4 rounded-xl bg-destructive/5 border border-destructive/20">
          <h4 className="text-xs font-bold text-destructive uppercase mb-2 flex items-center gap-2">
            <AlertCircle size={14} />
            Blockers
          </h4>
          <ul className="text-sm space-y-1 text-destructive/80">
            {blockers.map((item: string, i: number) => (
              <li key={i} className="flex gap-2">• {item}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  </div>
);

export default function StandupsPage() {
  const { user } = useUser();
  const standups = useQuery(api.activity.getStandups);
  const generateStandup = useAction(api.ai.generateStandup);
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async () => {
    if (!user?.fullName) return;
    setIsGenerating(true);
    try {
      await generateStandup({ author: user.fullName as string });
    } catch (err) {
      console.error(err);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="grid gap-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Standups</h1>
            <p className="text-muted-foreground">AI-generated daily work digests from commit history.</p>
          </div>
          <button 
            onClick={handleGenerate}
            disabled={isGenerating || !user}
            className="flex items-center gap-2 bg-secondary text-secondary-foreground px-6 py-3 rounded-full font-bold hover:bg-muted transition-colors disabled:opacity-50"
          >
            {isGenerating ? <Loader2 size={18} className="animate-spin text-primary" /> : <Sparkles size={18} className="text-primary" />}
            {isGenerating ? "Generating..." : "Generate New"}
          </button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {!standups ? (
            <div className="grid gap-6 animate-pulse w-full col-span-2 md:grid-cols-2">
              {[1, 2].map((i) => (
                <div key={i} className="h-64 bg-muted rounded-2xl" />
              ))}
            </div>
          ) : standups.length === 0 ? (
            <div className="col-span-2 p-20 text-center border-2 border-dashed rounded-[3rem] bg-card/30">
              <Calendar className="mx-auto text-muted-foreground mb-4 opacity-20" size={60} />
              <h3 className="text-xl font-bold mb-2">No Standups Yet</h3>
              <p className="text-muted-foreground max-w-xs mx-auto">Click "Generate New" to let AI summarize your recent activity.</p>
            </div>
          ) : (
            standups.map((standup) => (
              <StandupCard 
                key={standup._id}
                author={standup.author}
                date={standup.date}
                yesterday={standup.yesterday}
                today={standup.today}
                blockers={standup.blockers}
              />
            ))
          )}
        </div>
      </div>
    </DashboardLayout>
  );
}
