"use client";

import DashboardLayout from "@/components/dashboard-layout";
import { Calendar, User, CheckCircle2, Circle, AlertCircle, Sparkles } from "lucide-react";

const StandupCard = ({ author, yesterday, today, blockers }: any) => (
  <div className="p-6 rounded-2xl border bg-card/50 hover:border-primary/30 transition-all group">
    <div className="flex items-center gap-3 mb-6">
      <div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold">
        {author[0]}
      </div>
      <div>
        <h3 className="font-bold">{author}</h3>
        <p className="text-xs text-muted-foreground">Generated by AI Today at 8:30 AM</p>
      </div>
    </div>

    <div className="space-y-6">
      <div>
        <h4 className="text-xs font-bold text-muted-foreground uppercase mb-3 flex items-center gap-2">
          <CheckCircle2 size={14} className="text-green-500" />
          Yesterday
        </h4>
        <ul className="text-sm space-y-2 text-foreground/80">
          {yesterday.map((item: string, i: number) => (
            <li key={i} className="flex gap-2">
              <span className="text-primary">•</span> {item}
            </li>
          ))}
        </ul>
      </div>

      <div>
        <h4 className="text-xs font-bold text-muted-foreground uppercase mb-3 flex items-center gap-2">
          <Circle size={14} className="text-primary" />
          Today
        </h4>
        <ul className="text-sm space-y-2 text-foreground/80">
          {today.map((item: string, i: number) => (
            <li key={i} className="flex gap-2">
              <span className="text-primary">•</span> {item}
            </li>
          ))}
        </ul>
      </div>

      {blockers && blockers.length > 0 && (
        <div className="p-4 rounded-xl bg-destructive/5 border border-destructive/20">
          <h4 className="text-xs font-bold text-destructive uppercase mb-2 flex items-center gap-2">
            <AlertCircle size={14} />
            Blockers
          </h4>
          <ul className="text-sm space-y-1 text-destructive/80">
            {blockers.map((item: string, i: number) => (
              <li key={i} className="flex gap-2">• {item}</li>
            ))}
          </ul>
        </div>
      )}
    </div>
  </div>
);

export default function StandupsPage() {
  return (
    <DashboardLayout>
      <div className="grid gap-8">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Standups</h1>
            <p className="text-muted-foreground">AI-generated daily work digests from commit history.</p>
          </div>
          <button className="flex items-center gap-2 bg-secondary text-secondary-foreground px-6 py-3 rounded-full font-bold hover:bg-muted transition-colors">
            <Sparkles size={18} className="text-primary" />
            Generate New
          </button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <StandupCard 
            author="Akarsh Kushwaha"
            yesterday={[
                "Implemented GitHub Webhook API route",
                "Created Convex schema for tracking branch activity",
                "Built live conflict detection logic"
            ]}
            today={[
                "Integrating Clerk authentication with Convex",
                "Designing the dashboard layout and navigation",
                "Setting up real-time activity feed"
            ]}
            blockers={[
                "Waiting for GitHub App private key access"
            ]}
          />
          
          <StandupCard 
            author="GitHub Bot"
            yesterday={[
                "Auto-pushed 5 documentation updates",
                "Merged feat/ai-parser into main"
            ]}
            today={[
                "Scanning for stale branches",
                "Generating PR descriptions for 2 open PRs"
            ]}
          />
        </div>
      </div>
    </DashboardLayout>
  );
}
