"use client";

import { useState } from "react";
import DashboardLayout from "@/components/dashboard-layout";
import { FileText, Sparkles, Loader2, Calendar, Download } from "lucide-react";
import { useQuery, useAction } from "convex/react";
import { api } from "../../../../convex/_generated/api";
import ReactMarkdown from "react-markdown";

export default function ChangelogsPage() {
  const changelogs = useQuery(api.changelogs.getChangelogs);
  const generateChangelog = useAction(api.ai.generateChangelog);
  
  const [isGenerating, setIsGenerating] = useState(false);

  const handleGenerate = async () => {
    setIsGenerating(true);
    try {
      await generateChangelog({});
    } catch (err) {
      console.error(err);
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <DashboardLayout>
      <div className="grid gap-6">
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold tracking-tight">Changelogs</h1>
            <p className="text-muted-foreground">Automated weekly release notes generated by AI.</p>
          </div>
          <button
            onClick={handleGenerate}
            disabled={isGenerating}
            className="bg-primary text-primary-foreground px-4 py-2 rounded-xl font-bold flex items-center gap-2 hover:opacity-90 disabled:opacity-50 transition-opacity"
          >
            {isGenerating ? (
              <Loader2 size={18} className="animate-spin" />
            ) : (
              <Sparkles size={18} />
            )}
            {isGenerating ? "Generating..." : "Generate Weekly Digest"}
          </button>
        </div>

        <div className="grid gap-6">
          {!changelogs ? (
            <div className="flex flex-col gap-4 animate-pulse">
              {[1, 2].map((i) => (
                <div key={i} className="h-64 bg-muted rounded-2xl" />
              ))}
            </div>
          ) : changelogs.length === 0 ? (
            <div className="flex flex-col items-center justify-center p-20 border border-dashed rounded-2xl bg-card/50">
              <FileText className="text-primary mb-4" size={48} />
              <h3 className="text-xl font-bold">No Changelogs Found</h3>
              <p className="text-muted-foreground">Click generate to build your first release notes.</p>
            </div>
          ) : (
            changelogs.map((changelog) => (
              <div key={changelog._id} className="p-8 rounded-2xl border bg-card/50 hover:border-primary/50 transition-colors">
                <div className="flex items-center justify-between mb-6 pb-6 border-b">
                  <div className="flex items-center gap-4">
                    <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center text-primary">
                      <Calendar size={24} />
                    </div>
                    <div>
                      <h3 className="text-2xl font-bold">{changelog.title}</h3>
                      <p className="text-sm text-muted-foreground">
                        {new Date(changelog.startDate).toLocaleDateString()} - {new Date(changelog.endDate).toLocaleDateString()}
                      </p>
                    </div>
                  </div>
                  <button className="p-2 rounded-xl border bg-card hover:bg-muted transition-colors flex items-center gap-2 text-sm font-bold">
                    <Download size={16} /> Export
                  </button>
                </div>
                
                <div className="prose prose-invert max-w-none prose-headings:font-bold prose-a:text-primary">
                  <ReactMarkdown>{changelog.content}</ReactMarkdown>
                </div>
              </div>
            ))
          )}
        </div>
      </div>
    </DashboardLayout>
  );
}
