"use client";

/**
 * The Vendo client mount — generated by `vendo init`, then yours.
 * This "use client" boundary owns the registry and theme imports: the
 * registry carries component references, which cannot cross a Server
 * Component boundary as props (RSC serialization). <VendoOverlay /> is the
 * visible surface — the launcher pill + panel. Swap it for your own
 * surface (<VendoThread />, the BYO embeds) whenever you like.
 */
import { VendoOverlay, VendoRoot as VendoClientRoot } from "@vendoai/vendo/react";
import type { ReactNode } from "react";
import { registry } from "./registry";
import theme from "../../.vendo/theme.json";
import type { VendoTheme } from "@vendoai/vendo";

export function VendoRoot({ children }: { children: ReactNode }) {
  return (
    <VendoClientRoot components={registry} theme={theme as VendoTheme}>
      {children}
      <VendoOverlay />
    </VendoClientRoot>
  );
}
